name: Create a GitHub deployment
description: Create a new deployment in your repo.

inputs:
  github-token:
    description: |
      The Github Token to use. Must have access to repo.
    required: true
  ref:
    description: |
      The ref to dispatch. This can be a branch, tag, or SHA.
    default: ''
  workflow-id:
    description: |
      The ID of the workflow. You can also pass the workflow file name as a string.
    default: ''
  inputs:
    description: |
      Input keys and values configured in the workflow file. The maximum number of properties is 10. Any default properties configured in the workflow file will be used when inputs are omitted.
    default: ''

runs:
  using: 'node16'
  main: 'dist/index.js'