name: "Build and Push Python Package"
description: "Builds and pushes a python package from the given source. The package will be pushed to codeartifact"
inputs:
  aws-access-key-id:
    description: "The aws access key id used for login."
    required: true
  aws-secret-access-key:
    description: "The aws secret access key used for login."
    required: true
  aws-account-id:
    description: "The aws account id used for login."
    required: true
  role-external-id:
    description: "The external ID of the role to assume."
    required: true
  role-to-assume:
    description: "The role to assume."
    required: true
  aws-region:
    description: "AWS region of the codeartifact domain."
    required: true
  codeartifact-domain:
    description: "Domain of the aws codeartifact repository."
    required: true
  codeartifact-repository:
    description: "The aws codeartifact repository."
    required: true
  codeartifact-upstream-repository:
    description: "The aws codeartifact upstream repository."
    required: true
  git-user:
    description: "Git user to use for pushing the release on git."
    required: true
  git-email:
    description: "Git email to use for pushing the release on git."
    required: true
  gh-token:
    description: "The token to be used by python-semantic-release"
    required: true
outputs:
  published-release-version:
    description: "The version number which was released. Empty if no version was released."
    value: ${{ steps.build-and-push.outputs.total-coverage }}

runs:
  using: "composite"
  steps:
    - name: "Configure AWS Credentials"
      uses: kraussmaffei/actions/configure-aws-credentials@main
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        role-to-assume: ${{ inputs.role-to-assume }}
        role-external-id: ${{ inputs.role-external-id }}
        role-skip-session-tagging: true
        mask-aws-account-id: false
        aws-region: ${{ inputs.aws-region }}

    - name: "CodeArtifact login (pip)"
      uses: kraussmaffei/aws-tools-login@main
      with:
        account: ${{ inputs.aws-account-id }}
        region: ${{ inputs.aws-region }}
        aws-tool: "codeartifact-pip"
        codeartifact-domain: ${{ inputs.codeartifact-domain }}
        codeartifact-repository: ${{ inputs.codeartifact-repository }}

    - name: "CodeArtifact login (twine)"
      uses: kraussmaffei/aws-tools-login@main
      with:
        account: ${{ inputs.aws-account-id }}
        region: ${{ inputs.aws-region }}
        aws-tool: "codeartifact-twine"
        codeartifact-domain: ${{ inputs.codeartifact-domain }}
        codeartifact-repository: ${{ inputs.codeartifact-repository }}

    - name: Build and publish python package...
      id: build-and-push
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.gh-token }}
      run: |
        echo Configuring git...
        git config --global user.name ${{ inputs.git-user }}
        git config --global user.email ${{ inputs.git-email }}

        echo Installing required tools...
        pip install python-semantic-release poetry

        echo "::set-output name=published-release-version::$(semantic-release print-version)"
        semantic-release publish
