name: "Build"
on:
  pull_request:
  push:
    branches:
      - master
      - "feature/*"

jobs:
  test:
    name: "Test and Run"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: NPM Install
        run: npm ci
      - name: Test
        run: npm test
      - name: Package
        run: npm run package
      - name: Run Action
        uses: ./
        id: run
