name: 'Setup ssh-agent'
description: 'Setup the ssh-agent with an ssh-private-key and ssh-known-host'
inputs:
  ssh-private-key:
    required: true
  ssh-auth-sock:
    required: false
outputs:
  known-hosts-file-path:
    description: 'The path where the knonw host file is located at'
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/cleanup/index.js'