name: 'Setup ssh-agent'
description: 'Setup the ssh-agent with an ssh-private-key and ssh-known-host'
inputs:
  ssh-private-key:
    required: true
  ssh-auth-sock:
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/index.js'