name: "Run quality tasks"
description: "Runs all the necessary quality task for a given python project."
inputs:
  aws-access-key-id:
    description: "The aws access key id used for login."
    required: true
  aws-secret-access-key:
    description: "The aws secret access key used for login."
    required: true
  aws-account-id:
    description: "The aws account id used for login."
    required: true
  role-external-id:
    description: "The external ID of the role to assume."
    required: true
  role-to-assume:
    description: "The role to assume."
    required: true
  aws-region:
    description: "AWS region of the codeartifact domain."
    required: true
  codeartifact-domain:
    description: "Domain of the aws codeartifact repository."
    required: true
  codeartifact-repository:
    description: "The aws codeartifact repository."
    required: true
  python-package-path:
    description: "Path of the python package under quality test."
    required: true
  unit-test-file-pattern:
    description: "The pattern to search for unit test files."
    required: false
    default: "'test*.py'"
  python-version:
    description: "The python version to use for executing the quality tasks."
    required: false
    default: "3.8"
  ci-token:
    description: "The ci token to use."
    required: true
  sonar-token:
    description: "The token to use for sonarcloud."
    required: true

runs:
  using: "composite"
  steps:
    - name: "Setup Python"
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: "Configure AWS Credentials"
      uses: kraussmaffei/actions/configure-aws-credentials@main
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        role-to-assume: ${{ inputs.role-to-assume }}
        role-external-id: ${{ inputs.role-external-id }}
        role-skip-session-tagging: true
        mask-aws-account-id: false
        aws-region: ${{ inputs.aws-region }}

    - name: "CodeArtifact login (pip)"
      uses: kraussmaffei/aws-tools-login@main
      with:
        account: ${{ inputs.aws-account-id }}
        region: ${{ inputs.aws-region }}
        aws-tool: "codeartifact-pip"
        codeartifact-domain: ${{ inputs.codeartifact-domain }}
        codeartifact-repository: ${{ inputs.codeartifact-repository }}

    - name: Install required tools
      shell: bash
      run: |
        pip install coverage flake8
        pip install .[test-dependencies]

    - name: Running flake8 linter...
      shell: bash
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 ./${{ inputs.python-package-path }} --count --select=E9,F63,F7,F82 --builtins="_" --show-source --statistics

        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 ./${{ inputs.python-package-path }} --count --exit-zero --max-complexity=10 --builtins="_" --max-line-length=127 --statistics

    - name: Running coverage calculation...
      id: coverage-calculator
      shell: bash
      run: |
        coverage run --source=${{ inputs.python-package-path }} -m unittest discover -s tests -p ${{ inputs.unit-test-file-pattern }}
        coverage report -m
        coverage xml -o ./coverage-reports/coverage.xml

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ inputs.ci-token }}
        SONAR_TOKEN: ${{ inputs.sonar-token }}